version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: Install Now CLI
          command: sudo npm install -g --unsafe-perm now
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install NPM modules
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Deploy to Now
          command: |
            if [[ "$CIRCLE_BRANCH" == "master" ]]; then
              now --token $NOW_TOKEN --target production
            else
              now --token $NOW_TOKEN
            fi
workflows:
  version: 2
  release:
    jobs:
      - deploy
